model:
  backbone:
    network: "ResNet18"
  neck:
    network: "PANet"
    expansion: 1
    input_channels: [64, 128, 256, 512]
  head:
    network: "AnchorlessHead"
    num_classes: 90
    input_channels: [64, 128, 256, 512]
    num_prototypes: 8
    bg_index: 0
    image_size: [640, 640]

dataloader:
  dataset: "YoloDataset"
  dataset_path: "/home/lorrentz/DATA/coco/"
  image_size: [640, 640]
  batch_size: 2
  shuffle: True
  num_workers: 4
  pin_memory: False
  drop_last: True
  persistent_workers: False

training:
  epochs: 100
  validate_period: True
  device: 0
  log_path: "./log"
  optimizer:
    type: "AdamW"
    lr: 0.005
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0.01