model:
  backbone:
    network: "ResNet18"
  neck:
    network: "FPN"
    expansion: 1
    in_channels_list: [64, 128, 256, 512]
    out_channels: 256
  head:
    network: "DenseHead"
    num_classes: 90
    num_priors: 1
    input_channels: 256
    feat_channels: 256
    stacked_convs: 2
    num_prototypes: 8
    bg_index: 0
    image_size: [640, 640]

dataloader:
  dataset: "YoloDataset"
  dataset_path: "/home/lorrentz/DATA/coco/"
  image_size: [640, 640]
  batch_size: 4
  shuffle: True
  num_workers: 4
  pin_memory: False
  drop_last: True
  persistent_workers: False

training:
  epochs: 50
  validate_period: 
  device: 0
  optimizer: "Adam"